CFLAGS=-Wall -Wextra

all: linked_list.o test_linked_list todoer

test_linked_list: linked_list.o

todoer: linked_list.o

clean:
	rm -f todoer
	rm -f todo.txt
	rm -f linked_list.o
	rm -f test_linked_list
